### PR TITLE
Fix/add requirements

### PR DESCRIPTION
**Pull request by azribilel**
- update composer requirements
- fix deprecations 
- delete unused class calls

### CODE REVIEW

**Comment by devgiants** [comment]
Hey @azribilel ,

Why did you add JMS dependency as it is lch/translate-bundle core dependency? 
Thanks to remove it to avoid circular dependencies loop and/or divergent versions maintain problems.

Thanks a lot,

Nicolas

**Comment by devgiants** [comment]
Actually could you same PI on last tag please? It's on `develop`. `master ` is still far from actual `develop` state.

Thanks !

**Comment by azribilel** [comment]
> Hey @azribilel ,
> 
> Why did you add JMS dependency as it is lch/translate-bundle core dependency?
> Thanks to remove it to avoid circular dependencies loop and/or divergent versions maintain problems.
> 
> Thanks a lot,
> 
> Nicolas

I found this parameter 'jms_i18n_routing.default_locale' in service.yml, So i guessed the JMS i18n is required.
I will delete it

**Comment by azribilel** [comment]
I will close this and create a new clean pull request

**Pull request closed without merging**
